# Generated by Django 3.2.12 on 2022-02-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='token_type',
            field=models.CharField(choices=[('web', 'web'), ('mobile', 'mobile')], default='web', max_length=32),
        ),
    ]
