# Generated by Django 3.2.12 on 2023-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0010_alter_authtoken_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token_type',
            field=models.CharField(choices=[('mobile', 'mobile'), ('trusted_web', 'trusted_web'), ('web', 'web'), ('restricted', 'restricted')], default='web', max_length=32),
        ),
    ]
